### ISSUE TITLE
Drawing multiple messages between two activation bars

### ISSUE THREAD

**Issue by simondel** [violetumleditor/violetumleditor#3]
I am unable to create multiple message between two activation bars. I can create a call/create message and a return message but then I still can't follow it up with a new call/create message.

An example of this happening is:

![image](https://cloud.githubusercontent.com/assets/4221997/5437870/d81c8520-8473-11e4-933f-3a42e3798b3e.png)

In this image I have clicked Object1 and then clicked Object2. I would expect the purple line to get drawn, but it just disappears.

**Comment by bes1002t** [comment]
Why not creating new activation bars to connect both objects with multiple messages?
