### ISSUE TITLE
Support for Java > 8?

### ISSUE THREAD

**Issue by pohutukawa** [violetumleditor/violetumleditor#65]
I lvoe using Violet UML for quick sketching and thinking. I can still work it on Java 8 fine, however now with increasing availability of HiDPI/4k screens (e.g. my laptop), it's becoming increasingly harder to work with Violet UML on those, as only Java 9 has introduced proper HiDPI support for Linux.

I'd think it shouldn't be too hard to do, or is it?

I've been trying to run it using Amazon's Corretto JDK (11), which works in general (also quite snappy), however I'm getting quite significant rendering glitches. Same thing has happened with other more recent OpenJDK versions, so I always had to revert back to using Java 8, and see that I can only use Violet UML when I've got an external (normal DPI) screen available.

**Comment by alexdp** [comment]
Hi, 

Thank you very much for your feedback. Violet is now compiled with Java 17. I hope you will be able to try it again. 

Best, Alex
